# Modified from https://github.com/devcontainers/templates/blob/main/src/postgres/.devcontainer/docker-compose.yml

services:
  base:
    image: mcr.microsoft.com/devcontainers/universal:latest
    network_mode: service:db
  
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: